Algoritmo "Exerc1"

Var
        nf, nhtd,vpr,dm ,sal : real


Inicio
        Escreva("Digite seu número de incrição")
        Leia(nf)
        Escreva("Digite o número de horas trabalhadas por dia")
        Leia(nhtd)
        Escreva("Digite o valor por hora trabalhada")
        Leia(vpr)
        Escreva("Digite quantos dias trabalha em um mês")
        Leia(dm)
        sal<-((nhtd*vpr)*dm)
        Escreva("salário", sal)
        



Fimalgoritmo